config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "play" => "rounds#start", as: :new_round
  post "rounds/:id/guesses" => "rounds#new_guess", as: :new_guess

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/api_identifier.rb
class ApiIdentifier < ApplicationRecord
  belongs_to :identifiable, polymorphic: true

  validates :provider_name, presence: true

  validates :provider_id, presence: true, uniqueness: { scope: :provider_name }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/footballer.rb
class Footballer < ApplicationRecord
  
  FOOTBALLER_SCHEMA = Rails.root.join("app", "models", "schemas", "footballer_payload.json")

  validates :data, presence: true, json: { schema: FOOTBALLER_SCHEMA }
  validates :digest, presence: true

  store_accessor :data, :name, :common_name, :current_club, :nationality

  has_many :api_identifiers, as: :identifiable

  def self.random
    offset(rand(count)).limit(1).first
  end

  def self.generate_digest(name:, date_of_birth:, nationality:)
    Digest::SHA256.hexdigest("#{name.downcase.strip}#{date_of_birth.downcase.strip}#{nationality.downcase.strip}")
  end

  def build_prompt
    %{You are an AI assistant designed to participate in a guessing game about a mystery football player. 
    You will ONLY answer yes/no questions or respond to name guesses based solely on the context provided below.
    Respond with "Sorry, I can't answer that" to all other types of input.

    Context:
    "footballer": #{data}

    Rules:
    1. Only respond to yes/no questions about the player or attempts to guess the player's name. For all other types of input, including greetings, questions about yourself, how to play the game, or any non-yes/no questions, respond with "Sorry, I can't answer that". Before responding, think to determine if the question is a yes or no question, if it isn't, reply with "Sorry, I can't answer that"

    2. Use only the information provided in the context above to answer questions or respond to guesses.

    3.  If the user's guess or question about the player is correct according to the context, Respond with "Yes" and include the user's question in your response. For example:
    User: "Has the player won the Champions League?"
    Assistant: "Yes, the player has won the Champions League."

    4. If the user's guess or question about the player is incorrect according to the context, Respond with "No"  and Include the user's question in your response. For example:
    User: "Is it a Liverpool player?"
    Assistant: "No, it is not a Liverpool player."

    5. Respond with "Correct" if the user correctly guesses the full name OR any part of the name of the football player. For example, if the player's name is "Romelu Lukaku", respond with "Correct" for guesses of "Romelu Lukaku", "Romelu", or "Lukaku".

    6. Respond with "Sorry, I can't answer that" if the question cannot be answered based on the given context.

    7. Respond with "Sorry, I can't answer that" if the prompt is not a yes or no question. Respond with "Sorry, I can't answer that" for any questions that begin with "What", "Why", "How", "Who", "When", "Where", or any other question words that are not yes/no questions.

    8. Do not provide any additional information beyond what's asked in the question.

    9. Do not use any information not included in the context.

    Example interactions:

    User: Is the player a striker?
    Assistant: [Respond with "Yes, the player is a striker." or "No, the player is not a striker." based on the context]

    User: Has the player won the World Cup?
    Assistant: [Respond with "Yes, the player has won the World Cup." or "No, the player has not won the World Cup." based on the context]

    User: Is the player Lionel Messi?
    Assistant: [Respond with "Correct" if this is the correct name,]

    User: Is it Lukaku?
    Assistant: [Respond with "Correct" if Lukaku is part of the player's name]

    User: What is the player's favorite food?
    Assistant: [Respond with "Sorry, I can't answer that" if this information is not in the context]

    User: Does the player wear the no. 10?
    Assistant: [Respond with "Yes, the player wears no. 10." or "No, the player does not wear no. 10." based on the context]

    User: Hello
    Assistant: [Respond with "Sorry, I can't answer that" if it is not a yes or no question]

    User: Hello!
    Assistant: "Sorry, I can't answer that"

    User: How do I play this game?
    Assistant: Sorry, I can't answer that"

    User: Who are you?
    Assistant: Sorry, I can't answer that"

    User: What number does he wear?
    Assistant: Sorry, I can't answer that

    User: What team does he play for?
    Assistant: Sorry, I can't answer that

    User: What league does he play in?
    Assistant: Sorry, I can't answer that

    User: What is their name?
    Assistant: Sorry, I can't answer that

    User: What is their country?
    Assistant: Sorry, I can't answer that

    User: what country is he from?
    Assistant: Sorry, I can't answer that

    User: How old is the player
    Assistant:  Sorry, I can't answer that

    User: What's his position?
    Assistant: Sorry, I can't answer that

    Remember, your responses should include the context of the user's question for "Yes" or "No" answers, and be limited to "Correct" for correct name guesses. For questions that can't be answered, respond with "Sorry, I can't answer that". If the question is not a yes or no question, for example "What team does he play for?", "What number does he wear?" respond with "Sorry, I can't answer that" Always base your responses solely on the provided context about the football player.}
  end

end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :round
end

app/models/round.rb
class Round < ApplicationRecord
  MAX_ATTEMPTS = 10

  belongs_to :footballer

  has_many :guesses, dependent: :destroy

  def attempts_left
    MAX_ATTEMPTS - total_guesses
  end
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :api_identifiers, as: :identifiable

  validates :name, presence: true
  validates :league, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def start
    @footballer = Footballer.random
    @round = Round.create(footballer: @footballer)

    p @round
  end

  def new_guess
    @round = Round.find(params[:id])
    
    prompt = @round.footballer.build_prompt
    user_message = new_guess_params[:message]

    @response = GeminiAiService.new(max_output_tokens: 100).generate_content(user_message:, prompt:)
    @round.guesses.create!(message: user_message, response: @response)

    total_guesses = @round.total_guesses + 1
    if @response == "Correct"
      @round.update(result: :success, total_guesses:)
    else
      update = { total_guesses: }
      update[:result] = :failed if total_guesses >= Round::MAX_ATTEMPTS

      @round.update(update)
    end

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def new_guess_params
    params.require(:guess).permit(:message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/layouts/_navbar.html.erb
<header class="absolute inset-x-0 top-0 z-50">
  <nav class="flex items-center justify-between p-6 lg:px-8" aria-label="Global">
    <div class="flex lg:flex-1">
      <%= link_to root_path, class: "-m-1.5 p-1.5" do %>
        <span class="sr-only">Your Company</span>
        
        <%= image_tag "logo.png", class: "w-20" %>
      <% end %>
    </div>
    <div class="flex gap-x-12">
      <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Contact</a>
      <a href="#" class="text-sm font-semibold leading-6 text-gray-900">FAQ</a>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuessFootballer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto px-5">
      <%= render "layouts/navbar" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<main>
  <div class="bg-white">
    <div class="relative isolate px-6 pt-14 lg:px-8">
      <div class="mx-auto max-w-2xl py-32">
        <div class="text-center">
          <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">The Ultimate Football IQ Test</h1>
          <p class="mt-6 text-lg leading-8 text-gray-600">Do you love football? Put your football knowledge to the test by participating in fun challenges.</p>
          <div class="mt-10 flex items-center justify-center gap-x-6">
            <%= link_to 'Lets Play!', new_round_path, class: "rounded-md bg-green-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-green-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/rounds/_controls.html.erb
<%= turbo_frame_tag round, :controls do %>
  <% unless round.result %>
      <%= render "rounds/form" %>

      <div class="text-left w-full mt-7">
        <%= link_to new_round_path, class: "inline-block text-blue-500 text-sm flex items-center gap-x-2" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
            <path stroke-linecap="round" stroke-linejoin="round" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0 3.181 3.183a8.25 8.25 0 0 0 13.803-3.7M4.031 9.865a8.25 8.25 0 0 1 13.803-3.7l3.181 3.182m0-4.991v4.99" />
          </svg>
          Restart game
        <% end %>
      </div>
    <% end %>
<% end %>

app/views/rounds/_form.html.erb
<div class="flex justify-center w-full">
  <%= form_with model: Guess.new, 
      url: new_guess_path(@round.id), 
      class: "w-full group",
      data: {
        turbo_frame: dom_id(@round),
        controller: 'form',
        action: 'turbo:submit-end->form#onResponse'
      } do |form| %>
    <div class="flex gap-x-3 w-full">
      <div class="flex-grow">
        <%= form.label :message, class: "visually-hidden" %>
        <%= form.text_field :message, 
            required: true, 
            placeholder: "Ask a question", 
            autofocus: true,
            maxlength: 100,
            class: "block w-full rounded-md border-0 py-2.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-blue-400 sm:text-sm sm:leading-6 user_guess"
        %>
      </div>
      <%= button_tag(
          type: 'submit', 
          class: 'rounded-md bg-green-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-green-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 disabled:cursor-not-allowed'
          ) do %>
          <div class="group-aria-busy:block hidden">
            <svg xmlns="http://www.w3.org/2000/svg" class="size-6" viewBox="0 0 200 200"><circle fill="#FFFFFF" stroke="#FFFFFF" stroke-width="15" r="15" cx="40" cy="100"><animate attributeName="opacity" calcMode="spline" dur="2" values="1;0;1;" keySplines=".5 0 .5 1;.5 0 .5 1" repeatCount="indefinite" begin="-.4"></animate></circle><circle fill="#FFFFFF" stroke="#FFFFFF" stroke-width="15" r="15" cx="100" cy="100"><animate attributeName="opacity" calcMode="spline" dur="2" values="1;0;1;" keySplines=".5 0 .5 1;.5 0 .5 1" repeatCount="indefinite" begin="-.2"></animate></circle><circle fill="#FFFFFF" stroke="#FFFFFF" stroke-width="15" r="15" cx="160" cy="100"><animate attributeName="opacity" calcMode="spline" dur="2" values="1;0;1;" keySplines=".5 0 .5 1;.5 0 .5 1" repeatCount="indefinite" begin="0"></animate></circle></svg>
          </div>

          <div class="group-aria-busy:hidden flex gap-x-2 items-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 12 3.269 3.125A59.769 59.769 0 0 1 21.485 12 59.768 59.768 0 0 1 3.27 20.875L5.999 12Zm0 0h7.5" />
            </svg>
            Submit
          </div>
      <% end %>
    </div>
  <%  end %>
</div>

app/views/rounds/_result.html.erb
<%= turbo_frame_tag round do %>
  <% if round.result %>
    <div class="pt-12 pb-8">
      <p class="text-2xl font-semibold text-center mb-2 text-gray-800"> <%= round.result == "success" ? "Congratulations! You got it right!" : "Game over! You've used all your tries."  %> </p>
      <p class="text-gray-600 text-md text-center">
        <%= round.result == "success" ? 
              " The player is #{round.footballer.name}. It took you only #{round.total_guesses} attempts 😄" 
              : "Too bad. You had #{round.total_guesses} attempts, but you couldn't meet the target! The player is #{round.footballer.common_name} of #{round.footballer.current_club}." %>
      </p>
    </div>
    <div class="flex justify-center space-x-6 items-center mb-4">
      <%= link_to new_round_path, class: "inline-block text-blue-500 text-sm flex items-center gap-x-2", data: { turbo_frame: "_top" } do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
          <path stroke-linecap="round" stroke-linejoin="round" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0 3.181 3.183a8.25 8.25 0 0 0 13.803-3.7M4.031 9.865a8.25 8.25 0 0 1 13.803-3.7l3.181 3.182m0-4.991v4.99" />
        </svg>
        Play again
      <% end %>
      <%= link_to root_path, class: "inline-block text-blue-500 text-sm flex items-center gap-x-2" do %>
        Go Home
      <% end %>
    </div>
  <% else %>
    <p class="text-2xl font-semibold py-10 text-center text-gray-800"><%= response %></p>
    <p class="text-sm text-gray-500 w-full text-left mb-3">You have <%= round.attempts_left %> tries left</p>
  <% end %>
<% end %>

app/views/rounds/_tries.html.erb
<p class="text-sm text-gray-500 w-full text-left mb-3">You have 8 tries left</p>

app/views/rounds/new_guess.turbo_stream.erb
<%= turbo_stream.replace @round do %>
  <%= render "rounds/result", round: @round, response: @response %>
<% end %>

<%= turbo_stream.replace dom_id(@round, :controls) do %>
  <%= render "rounds/controls", round: @round %>
<% end %>

app/views/rounds/start.html.erb
<div class="relative isolate px-4 pt-14 lg:px-8 max-w-xl mx-auto">
  <div class=" mt-20 flex flex-col items-center">
    <%=image_tag("avatar-bw.png", alt: "Example Image", class: "size-16 rounded-full mb-8")%>
    <p class="text-md text-center text-gray-700">I am thinking of a mystery footballer. Try to guess who it is by asking yes or no questions.</p>
    <div class="w-full">
      <%= render "rounds/result", round: @round, response: nil, result: "success" %>
    </div>
    
    <%= render "rounds/controls", round: @round %>

  </div>
</div>